name: test

#on:
#  push:
#  workflow_dispatch:
##    inputs:
##      your_name:
##        required: true
##        type: string
##      your_age:
##        required: true
##        type: integer
#
#jobs:
#  hello-spring-boot:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#      - run: chmod +x gradlew
#      - run: ./gradlew clean build test
#      - run: echo "Hello, ${{ inputs.your_name }}"
#      - run: echo "Your age is ${{ inputs.your_age }}"
on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        description: name
        type: string
      age:
        required: false
        description: age
        type: string


jobs:
  hello-spring-boot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: chmod +x gradlew
      - run: ./gradlew clean build test
      - run: echo "Hello, ${{ inputs.your_name }}"
      - run: echo "Your age is ${{ inputs.your_age }}"